# Changes here will be overwritten by Copier
_commit: 85694ff
_src_path: gh:34j/pypackage-template
add_me_as_contributor: true
cli_name: aoiro
copyright_year: '2025'
documentation: true
email: 34j.github@proton.me
full_name: 34j
github_username: 34j
has_cli: true
initial_commit: true
is_django_package: false
open_source_license: GNU General Public License v3
open_with_editor: true
package_name: aoiro
project_name: Aoiro
project_short_description: CSV-based 青色申告 CLI app
project_slug: aoiro
run_poetry_install: true
setup_github: true
setup_pre_commit: true

