# Changes here will be overwritten by Copier
_commit: af9b795
_src_path: gh:34j/pypackage-template
cli_name: aoiro
copyright_year: '2025'
documentation: true
email: 34j.github@proton.me
full_name: 34j
github_username: 34j
has_cli: true
initial_commit: false
is_django_package: false
open_source_license: MIT
open_with_editor: true
package_name: aoiro
project_name: Aoiro
project_short_description: CSV-based 青色申告 CLI app
project_slug: aoiro
run_uv_sync: false
setup_github: false
setup_pre_commit: false

